<?php

namespace TripSorter\Tests\Entity\Transportation;

use TripSorter\Entity\Transportation\BusBoardingCard;
use PHPUnit_Framework_TestCase;

/**
 * Test class for {@link \TripSorter\Entity\Transportation\BusBoardingCard}
 */
class BusBoardingCardTest extends PHPUnit_Framework_TestCase
{

    /**
     * System under test
     *
     * @var BusBoardingCard
     */
    private $sut;

    /**
     * {@inheritdoc}
     */
    public function setUp()
    {
        $this->sut = new BusBoardingCard();
        $this->sut->setOrigin('Barcelona');
        $this->sut->setDestination('Gerona Airport');
    }

    /**
     * Test function getDescription
     */
    public function testGetDescription()
    {
        static::assertSame(
            'Take bus from Barcelona to Gerona Airport. No seat assignment.',
            $this->sut->getDescription(),
            'Wrong description generated by boarding card.'
        );
    }

}
