<?php

namespace TripSorter\Tests\Entity\Transportation;

use PHPUnit_Framework_TestCase;
use TripSorter\Entity\Transportation\TrainBoardingCard;

/**
 * Test class for {@link \TripSorter\Entity\Transportation\TrainBoardingCard}
 */
class TrainBoardingCardTest extends PHPUnit_Framework_TestCase
{

    /**
     * System under test
     *
     * @var TrainBoardingCard
     */
    private $sut;

    /**
     * {@inheritdoc}
     */
    public function setUp()
    {
        $this->sut = new TrainBoardingCard();
        $this->sut->setNumber('78A');
        $this->sut->setOrigin('Madrid');
        $this->sut->setDestination('Barcelona');
        $this->sut->setSeatAssignment('45B');
    }

    /**
     * Test function getDescription
     */
    public function testGetDescription()
    {
        static::assertSame(
            'Take train 78A from Madrid to Barcelona. Sit in seat 45B.',
            $this->sut->getDescription(),
            'Wrong description generated by boarding card.'
        );
    }

}
